apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.metadata.name }}
  namespace: {{ .Values.ingress.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: {{ .Values.ingress.metadata.name }}
    meta.helm.sh/release-namespace: {{ .Values.ingress.metadata.namespace }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: 8080
            path: {{ .Values.ingress.data.path }}
            pathType: Prefix