apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.service.labels.app }}
    meta.helm.sh/release-namespace: {{ .Values.service.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app: {{ .Values.service.labels.app }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.service.labels.app }}
  sessionAffinity: None
  type: ClusterIP
