feignClient:
  rulesPersistenceEngine: ${FEIGNCLIENT_RULESPERSISTENCEENGINE:http://localhost:8081/}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:RulesEngine}
      username: ${SPRING_DATA_MONGODB_USERNAME:''}
      password: ${SPRING_DATA_MONGODB_PASSWORD:''}
  jpa:
    show-sql: ${SPRING_JPA_SHOWSQL:false}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

server:
  port: ${SERVER_PORT:8081}

mongo:
  ssl:
    invalidHostNameAllowed: ${MONGO_SSL_INVALIDHOSTNAMEALLOWED:false}
    enabled: ${MONGO_SSL_ENABLED:false}
    pem: ${MONGO_SSL_PEM:C:\\Users\\antonio.cuomo\\accenture-workspace\\rules-persistence-engine\\cce-server.pem}
  passwordLess: ${MONGO_PASSWORDLESS:true}
  authenticationMechanisms: ${MONGO_AUTHENTICATIONMECHANISMS:default}